Task 1

In [2]:
def convert_length(value, unit):
    """
    Converts length between meters and feet.
    :param value: The numerical value to be converted.
    :param unit: The unit of the given value ('m' for meters, 'ft' for feet).
    :return: Converted value with the appropriate unit.
    """
    if unit == "m":
        return value * 3.28084, "ft"
    elif unit == "ft":
        return value / 3.28084, "m"
    else:
        raise ValueError("Unsupported unit for length conversion.")

def convert_weight(value, unit):
    """
    Converts weight between kilograms and pounds.
    :param value: The numerical value to be converted.
    :param unit: The unit of the given value ('kg' for kilograms, 'lbs' for pounds).
    :return: Converted value with the appropriate unit.
    """
    if unit == "kg":
        return value * 2.20462, "lbs"
    elif unit == "lbs":
        return value / 2.20462, "kg"
    else:
        raise ValueError("Unsupported unit for weight conversion.")

def convert_volume(value, unit):
    """
    Converts volume between liters and gallons.
    :param value: The numerical value to be converted.
    :param unit: The unit of the given value ('L' for liters, 'gal' for gallons).
    :return: Converted value with the appropriate unit.
    """
    if unit == "L":
        return value * 0.264172, "gal"
    elif unit == "gal":
        return value / 0.264172, "L"
    else:
        raise ValueError("Unsupported unit for volume conversion.")

def main():
    """Main function to handle user input and perform conversions."""
    print("Unit Converter: Choose a conversion type")
    print("1. Length (m <-> ft)")
    print("2. Weight (kg <-> lbs)")
    print("3. Volume (L <-> gal)")

    try:
        choice = int(input("Enter your choice (1-3): "))
        value = float(input("Enter the value to convert: "))
        unit = input("Enter the unit (m, ft, kg, lbs, L, gal): ").strip()

        if choice == 1:
            converted_value, new_unit = convert_length(value, unit)
        elif choice == 2:
            converted_value, new_unit = convert_weight(value, unit)
        elif choice == 3:
            converted_value, new_unit = convert_volume(value, unit)
        else:
            print("Invalid choice! Please enter a number between 1 and 3.")
            return

        print(f"Converted Value: {converted_value:.2f} {new_unit}")
    except ValueError as e:
        print(f"Error: {e}. Please enter a valid number and unit.")
    except Exception as e:
        print(f"Unexpected error: {e}")

if __name__ == "__main__":
    main()


Unit Converter: Choose a conversion type
1. Length (m <-> ft)
2. Weight (kg <-> lbs)
3. Volume (L <-> gal)
Enter your choice (1-3): 2
Enter the value to convert: 6
Enter the unit (m, ft, kg, lbs, L, gal): kg
Converted Value: 13.23 lbs


Task- 2

In [3]:
def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.
    :param numbers: List of numerical values.
    :return: Sum of the numbers.
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.
    :param numbers: List of numerical values.
    :return: Average of the numbers.
    """
    return sum(numbers) / len(numbers) if numbers else 0

def find_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.
    :param numbers: List of numerical values.
    :return: Maximum number in the list.
    """
    return max(numbers)

def find_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.
    :param numbers: List of numerical values.
    :return: Minimum number in the list.
    """
    return min(numbers)

def main():
    """Main function to handle user input and perform mathematical operations."""
    print("Mathematical Operations on a List of Numbers")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = int(input("Enter your choice (1-4): "))
        numbers = list(map(float, input("Enter a list of numbers separated by spaces: ").split()))

        if not numbers:
            raise ValueError("The list cannot be empty.")

        if choice == 1:
            result = calculate_sum(numbers)
        elif choice == 2:
            result = calculate_average(numbers)
        elif choice == 3:
            result = find_maximum(numbers)
        elif choice == 4:
            result = find_minimum(numbers)
        else:
            print("Invalid choice! Please enter a number between 1 and 4.")
            return

        print(f"Result: {result:.2f}")
    except ValueError as e:
        print(f"Error: {e}. Please enter valid numeric values.")
    except Exception as e:
        print(f"Unexpected error: {e}")

if __name__ == "__main__":
    main()

Mathematical Operations on a List of Numbers
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 1
Enter a list of numbers separated by spaces: 1 2 3 4
Result: 10.00


 Exercise on List Manipulation:

 1. Extract Every Other Element:

In [4]:
def extract_every_other(lst):
    """
    Extracts every other element from a list, starting from the first element.
    :param lst: List of elements.
    :return: A new list containing every other element.
    """
    return lst[::2]

# Example usage:
sample_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(sample_list)
print(result)

[1, 3, 5]


 2. Slice a Sublist

In [8]:

def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list, including the start and end indices.
    :param lst: List of elements.
    :param start: Starting index (inclusive).
    :param end: Ending index (inclusive).
    :return: A sublist from start to end.
    """
    return lst[start:end+1]

# Example usage:
sample_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(sample_list)
print(result)  # Output: [1, 3, 5]

sublist_result = get_sublist(sample_list, 2, 4)
print(sublist_result)

[1, 3, 5]
[3, 4, 5]


3. Reverse a List Using Slicing

In [7]:
def reverse_list(lst):
    """
    Reverses a list using slicing.
    :param lst: List of elements.
    :return: A new list with elements in reverse order.
    """
    return lst[::-1]

# Example usage:
sample_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(sample_list)
print(result)  # Output: [1, 3, 5]

sublist_result = get_sublist(sample_list, 2, 4)
print(sublist_result)  # Output: [3, 4, 5]

reversed_result = reverse_list(sample_list)
print(reversed_result)

[1, 3, 5]
[3, 4, 5]
[6, 5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

In [9]:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list and returns the resulting sublist.
    :param lst: List of elements.
    :return: A sublist without the first and last elements.
    """
    return lst[1:-1]

# Example usage:
sample_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(sample_list)
print(result)  # Output: [1, 3, 5]

sublist_result = get_sublist(sample_list, 2, 4)
print(sublist_result)  # Output: [3, 4, 5]

reversed_result = reverse_list(sample_list)
print(reversed_result)  # Output: [6, 5, 4, 3, 2, 1]

trimmed_result = remove_first_last(sample_list)
print(trimmed_result)

[1, 3, 5]
[3, 4, 5]
[6, 5, 4, 3, 2, 1]
[2, 3, 4, 5]


 5. Get the First n Elements:

In [10]:
def get_first_n(lst, n):
    """
    Extracts the first n elements from a list.
    :param lst: List of elements.
    :param n: Number of elements to extract.
    :return: A new list containing the first n elements.
    """
    return lst[:n]

# Example usage:
sample_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(sample_list)
print(result)  # Output: [1, 3, 5]

sublist_result = get_sublist(sample_list, 2, 4)
print(sublist_result)  # Output: [3, 4, 5]

reversed_result = reverse_list(sample_list)
print(reversed_result)  # Output: [6, 5, 4, 3, 2, 1]

trimmed_result = remove_first_last(sample_list)
print(trimmed_result)  # Output: [2, 3, 4, 5]

first_n_result = get_first_n(sample_list, 3)
print(first_n_result)

[1, 3, 5]
[3, 4, 5]
[6, 5, 4, 3, 2, 1]
[2, 3, 4, 5]
[1, 2, 3]


6. Extract Elements from the End:

In [12]:
def extract_every_other(lst):
    """
    Extracts every other element from a list, starting from the first element.
    :param lst: List of elements.
    :return: A new list containing every other element.
    """
    return lst[::2]

def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list, including the start and end indices.
    :param lst: List of elements.
    :param start: Starting index (inclusive).
    :param end: Ending index (inclusive).
    :return: A sublist from start to end.
    """
    return lst[start:end+1]

def reverse_list(lst):
    """
    Reverses a list using slicing.
    :param lst: List of elements.
    :return: A new list with elements in reverse order.
    """
    return lst[::-1]

def remove_first_last(lst):
    """
    Removes the first and last elements of a list and returns the resulting sublist.
    :param lst: List of elements.
    :return: A sublist without the first and last elements.
    """
    return lst[1:-1]

def get_first_n(lst, n):
    """
    Extracts the first n elements from a list.
    :param lst: List of elements.
    :param n: Number of elements to extract.
    :return: A new list containing the first n elements.
    """
    return lst[:n]

def get_last_n(lst, n):
    """
    Extracts the last n elements from a list.
    :param lst: List of elements.
    :param n: Number of elements to extract from the end.
    :return: A new list containing the last n elements.
    """
    return lst[-n:]

# Example usage:
sample_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(sample_list)
print(result)  # Output: [1, 3, 5]

sublist_result = get_sublist(sample_list, 2, 4)
print(sublist_result)  # Output: [3, 4, 5]

reversed_result = reverse_list(sample_list)
print(reversed_result)  # Output: [6, 5, 4, 3, 2, 1]

trimmed_result = remove_first_last(sample_list)
print(trimmed_result)  # Output: [2, 3, 4, 5]

first_n_result = get_first_n(sample_list, 3)
print(first_n_result)  # Output: [1, 2, 3]

last_n_result = get_last_n(sample_list, 2)
print(last_n_result)

[1, 3, 5]
[3, 4, 5]
[6, 5, 4, 3, 2, 1]
[2, 3, 4, 5]
[1, 2, 3]
[5, 6]


 7. Extract Elements in Reverse Order

In [13]:
def reverse_skip(lst):
    """
    Extracts elements in reverse order, starting from the second-to-last element and skipping one in between.
    :param lst: List of elements.
    :return: A new list containing every second element in reverse order.
    """
    return lst[-2::-2]

# Example usage:
sample_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(sample_list)
print(result)  # Output: [1, 3, 5]

sublist_result = get_sublist(sample_list, 2, 4)
print(sublist_result)  # Output: [3, 4, 5]

reversed_result = reverse_list(sample_list)
print(reversed_result)  # Output: [6, 5, 4, 3, 2, 1]

trimmed_result = remove_first_last(sample_list)
print(trimmed_result)  # Output: [2, 3, 4, 5]

first_n_result = get_first_n(sample_list, 3)
print(first_n_result)  # Output: [1, 2, 3]

last_n_result = get_last_n(sample_list, 2)
print(last_n_result)  # Output: [5, 6]

reverse_skip_result = reverse_skip(sample_list)
print(reverse_skip_result)


[1, 3, 5]
[3, 4, 5]
[6, 5, 4, 3, 2, 1]
[2, 3, 4, 5]
[1, 2, 3]
[5, 6]
[5, 3, 1]


 4.3 Exercise on Nested List:

 1. Flatten a Nested List:

In [14]:
def flatten(lst):
    """
    Flattens a nested list into a single list.
    :param lst: Nested list of elements.
    :return: A flattened list with all elements in a single dimension.
    """
    return [item for sublist in lst for item in sublist]

# Example usage:
sample_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(sample_list)
print(result)  # Output: [1, 3, 5]

sublist_result = get_sublist(sample_list, 2, 4)
print(sublist_result)  # Output: [3, 4, 5]

reversed_result = reverse_list(sample_list)
print(reversed_result)  # Output: [6, 5, 4, 3, 2, 1]

trimmed_result = remove_first_last(sample_list)
print(trimmed_result)  # Output: [2, 3, 4, 5]

first_n_result = get_first_n(sample_list, 3)
print(first_n_result)  # Output: [1, 2, 3]

last_n_result = get_last_n(sample_list, 2)
print(last_n_result)  # Output: [5, 6]

reverse_skip_result = reverse_skip(sample_list)
print(reverse_skip_result)  # Output: [5, 3, 1]

nested_list = [[1, 2], [3, 4], [5]]
flattened_result = flatten(nested_list)
print(flattened_result)

[1, 3, 5]
[3, 4, 5]
[6, 5, 4, 3, 2, 1]
[2, 3, 4, 5]
[1, 2, 3]
[5, 6]
[5, 3, 1]
[1, 2, 3, 4, 5]


 2. Accessing Nested List Elements:

In [15]:
def access_nested_element(lst, indices):
    """
    Extracts a specific element from a nested list given its indices.
    :param lst: Nested list of elements.
    :param indices: List of indices to access the desired element.
    :return: The element at the specified indices.
    """
    element = lst
    for index in indices:
        element = element[index]
    return element

# Example usage:
sample_list = [1, 2, 3, 4, 5, 6]
result = extract_every_other(sample_list)
print(result)  # Output: [1, 3, 5]

sublist_result = get_sublist(sample_list, 2, 4)
print(sublist_result)  # Output: [3, 4, 5]

reversed_result = reverse_list(sample_list)
print(reversed_result)  # Output: [6, 5, 4, 3, 2, 1]

trimmed_result = remove_first_last(sample_list)
print(trimmed_result)  # Output: [2, 3, 4, 5]

first_n_result = get_first_n(sample_list, 3)
print(first_n_result)  # Output: [1, 2, 3]

last_n_result = get_last_n(sample_list, 2)
print(last_n_result)  # Output: [5, 6]

reverse_skip_result = reverse_skip(sample_list)
print(reverse_skip_result)  # Output: [5, 3, 1]

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
flattened_result = flatten(nested_list)
print(flattened_result)  # Output: [1, 2, 3, 4, 5, 6, 7, 8, 9]

nested_element = access_nested_element(nested_list, [1, 2])
print(nested_element)

[1, 3, 5]
[3, 4, 5]
[6, 5, 4, 3, 2, 1]
[2, 3, 4, 5]
[1, 2, 3]
[5, 6]
[5, 3, 1]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
6


3. Sum of All Elements in a Nested List

In [17]:
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list.
    :param lst: Nested list of numbers.
    :return: The sum of all numbers in the nested list.
    """
    def flatten(nested_list):
        """Helper function to flatten a nested list."""
        result = []
        for item in nested_list:
            if isinstance(item, list):
                result.extend(flatten(item))
            else:
                result.append(item)
        return result

    return sum(flatten(lst))

# Example usage:
print(sum_nested([[1, 2], [3, [4, 5]], 6]))  # Output: 21


21


4. Remove Specific Element from a Nested List

In [18]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.
    :param lst: Nested list of elements.
    :param elem: Element to be removed.
    :return: The modified list without the specified element.
    """
    if isinstance(lst, list):
        return [remove_element(item, elem) for item in lst if item != elem]
    else:
        return lst

# Example usage:
nested_list = [[1, 2], [3, 2], [4, 5]]
element_to_remove = 2
print(remove_element(nested_list, element_to_remove))  # Output: [[1], [3], [4, 5]]


[[1], [3], [4, 5]]


 5. Find the Maximum Element in a Nested List
6. Count Occurrences of an Element in a Nested List:
7. Flatten a List of Lists of Lists
8. Nested List Average:


In [20]:


def extract_every_other(lst):
    """Extracts every other element from a list, starting from the first element."""
    return lst[::2]

def get_sublist(lst, start, end):
    """Returns a sublist from start to end (inclusive)."""
    return lst[start:end+1]

def reverse_list(lst):
    """Reverses a list using slicing."""
    return lst[::-1]

def remove_first_last(lst):
    """Removes the first and last elements of a list and returns the resulting sublist."""
    return lst[1:-1]

def get_first_n(lst, n):
    """Extracts the first n elements from a list."""
    return lst[:n]

def get_last_n(lst, n):
    """Extracts the last n elements of a list."""
    return lst[-n:]

def reverse_skip(lst):
    """Extracts elements in reverse order, starting from the second-to-last element and skipping one in between."""
    return lst[-2::-2]

def flatten(lst):
    """Flattens a nested list into a single list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result

def access_nested_element(lst, indices):
    """Extracts a specific element from a nested list given its indices."""
    element = lst
    for index in indices:
        element = element[index]
    return element

def sum_nested(lst):
    """Calculates the sum of all numbers in a nested list."""
    return sum(flatten(lst))

def remove_element(lst, elem):
    """Removes all occurrences of a specific element from a nested list."""
    return [[item for item in sublist if item != elem] for sublist in lst]

def find_max_element(lst):
    """Finds the maximum element in a nested list."""
    return max(flatten(lst))

def count_occurrences(lst, elem):
    """Counts the occurrences of a specific element in a nested list."""
    return flatten(lst).count(elem)

def deep_flatten(lst):
    """Flattens a deeply nested list into a single list."""
    return flatten(lst)

def average_nested(lst):
    """Calculates the average of all elements in a nested list."""
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list) if flat_list else 0

# Example usage:
sample_list = [1, 2, 3, 4, 5, 6]
print(extract_every_other(sample_list))  # Output: [1, 3, 5]
print(get_sublist(sample_list, 2, 4))  # Output: [3, 4, 5]
print(reverse_list(sample_list))  # Output: [6, 5, 4, 3, 2, 1]
print(remove_first_last(sample_list))  # Output: [2, 3, 4, 5]
print(get_first_n(sample_list, 3))  # Output: [1, 2, 3]
print(get_last_n(sample_list, 2))  # Output: [5, 6]
print(reverse_skip(sample_list))  # Output: [5, 3, 1]

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(flatten(nested_list))  # Output: [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(access_nested_element(nested_list, [1, 2]))  # Output: 6
print(sum_nested([[1, 2], [3, [4, 5]], 6]))  # Output: 21
print(remove_element([[1, 2], [3, 2], [4, 5]], 2))  # Output: [[1], [3], [4, 5]]
print(find_max_element([[1, 2], [3, [4, 5]], 6]))  # Output: 6
print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))  # Output: 3
print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))  # Output: [1, 2, 3, 4, 5, 6, 7, 8]
print(average_nested([[1, 2], [3, 4], [5, 6]]))  # Output: 3.5


[1, 3, 5]
[3, 4, 5]
[6, 5, 4, 3, 2, 1]
[2, 3, 4, 5]
[1, 2, 3]
[5, 6]
[5, 3, 1]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
6
21
[[1], [3], [4, 5]]
6
3
[1, 2, 3, 4, 5, 6, 7, 8]
3.5


 10 To- Do- NumPy

Problem- 1: Array Creation:

In [21]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty Array:")
print(empty_array)

# 2. Initialize an all-ones array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll Ones Array:")
print(ones_array)

# 3. Return a new array of given shape and type, filled with fill value
fill_value = 7  # Example fill value
filled_array = np.full((3, 3), fill_value)
print("\nFilled Array:")
print(filled_array)

# 4. Return a new array of zeros with the same shape and type as a given array
reference_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(reference_array)
print("\nZeros Like Array:")
print(zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(reference_array)
print("\nOnes Like Array:")
print(ones_like_array)

# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array:")
print(numpy_array)


Empty Array:
[[2.41917667e-316 0.00000000e+000]
 [6.93555648e-310 2.26368561e-076]]

All Ones Array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled Array:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like Array:
[[0 0 0]
 [0 0 0]]

Ones Like Array:
[[1 1 1]
 [1 1 1]]

Converted NumPy Array:
[1 2 3 4]


Problem- 2: Array Manipulation: Numerical Ranges and Array indexing

In [22]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty Array:")
print(empty_array)

# 2. Initialize an all-ones array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll Ones Array:")
print(ones_array)

# 3. Return a new array of given shape and type, filled with fill value
fill_value = 7  # Example fill value
filled_array = np.full((3, 3), fill_value)
print("\nFilled Array:")
print(filled_array)

# 4. Return a new array of zeros with the same shape and type as a given array
reference_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(reference_array)
print("\nZeros Like Array:")
print(zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(reference_array)
print("\nOnes Like Array:")
print(ones_like_array)

# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array:")
print(numpy_array)

# Problem-2: Array Manipulation: Numerical Ranges and Array Indexing

# 1. Create an array with values ranging from 10 to 49
range_array = np.arange(10, 50)
print("\nArray with values from 10 to 49:")
print(range_array)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape((3, 3))
print("\n3x3 Matrix with values from 0 to 8:")
print(matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:")
print(identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array of size 30:")
print(random_array)
print("Mean of the array:", mean_value)

# 5. Create a 10x10 array with random values and find min & max
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("\n10x10 Random Matrix:")
print(random_matrix)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th element as 1:")
print(zero_array)

# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:")
print(reversed_arr)

# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with border 1 and inside 0:")
print(border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:")
print(checkerboard)

Empty Array:
[[2.38440493e-316 0.00000000e+000]
 [4.94065646e-324             nan]]

All Ones Array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled Array:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like Array:
[[0 0 0]
 [0 0 0]]

Ones Like Array:
[[1 1 1]
 [1 1 1]]

Converted NumPy Array:
[1 2 3 4]

Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of size 30:
[0.09701993 0.99845569 0.48226102 0.02628575 0.8304051  0.36429959
 0.78329472 0.33206931 0.07203506 0.78978613 0.37345306 0.78279233
 0.91543849 0.83588721 0.36665162 0.86614229 0.20860364 0.42654784
 0.99791668 0.96570565 0.10605733 0.73345232 0.00453311 0.77903121
 0.01718029 0.21198821 0.46780973 0.82962913 0.30830611 0.93451567]
Mean of the array: 0.5302518064662558

10x10 Random Matrix:
[[0.488

 Problem- 3: Array Operations:

In [24]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("\nAddition of x and y:")
print(add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\nSubtraction of x and y:")
print(sub_xy)

# 3. Multiply the array with an integer
mult_x = x * 3
print("\nMultiplication of x with 3:")
print(mult_x)

# 4. Find the square of each element of the array
square_x = x ** 2
print("\nSquare of each element in x:")
print(square_x)

# 5. Find the dot product
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nDot product of v and w:", dot_vw)
print("Dot product of x and v:")
print(dot_xv)
print("Dot product of x and y:")
print(dot_xy)

# 6. Concatenate x and y along rows, v and w along columns
concat_xy = np.concatenate((x, y), axis=0)
concat_vw = np.vstack((v, w))
print("\nConcatenation of x and y along rows:")
print(concat_xy)
print("\nConcatenation of v and w along columns:")
print(concat_vw)

# 7. Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenation of x and v:")
    print(concat_xv)
except ValueError as e:
    print("\nError in concatenating x and v:", e)
    print("Explanation: x is a 2x2 matrix while v is a 1D array. The dimensions do not match for concatenation along any axis.")

    v_reshaped = v.reshape(1, -1)  # Reshape v to a 2D array of shape (1,2)
concat_xv_fixed = np.concatenate((x, v_reshaped), axis=0)
print("\nConcatenation of x and v after reshaping v:")
print(concat_xv_fixed)




Addition of x and y:
[[ 6  8]
 [10 13]]

Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

Multiplication of x with 3:
[[ 3  6]
 [ 9 15]]

Square of each element in x:
[[ 1  4]
 [ 9 25]]

Dot product of v and w: 219
Dot product of x and v:
[29 77]
Dot product of x and y:
[[19 22]
 [50 58]]

Concatenation of x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
[[ 9 10]
 [11 12]]

Error in concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is a 2x2 matrix while v is a 1D array. The dimensions do not match for concatenation along any axis.

Concatenation of x and v after reshaping v:
[[ 1  2]
 [ 3  5]
 [ 9 10]]


 Problem- 4: Matrix Operations:

In [25]:
import numpy as np

# Define matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^-1:")
print(identity_matrix)

# 2. Check if AB == BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:")
print(AB)
print("BA:")
print(BA)
print("Is AB equal to BA?:", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("(AB)^T:")
print(AB_T)
print("B^T * A^T:")
print(BT_AT)
print("Is (AB)^T equal to B^T A^T?:", np.array_equal(AB_T, BT_AT))

# Solve the system of linear equations using inverse method
A_system = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_system = np.array([-1, -3, 9])

# Compute solution X = A^-1 * B
A_inv_system = np.linalg.inv(A_system)
X = np.dot(A_inv_system, B_system)
print("Solution for x, y, z:")
print(X)

A * A^-1:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
Is AB equal to BA?: False
(AB)^T:
[[23 51]
 [13 29]]
B^T * A^T:
[[23 51]
 [13 29]]
Is (AB)^T equal to B^T A^T?: True
Solution for x, y, z:
[ 2.  1. -2.]


 10.2 Experiment: How Fast is Numpy?

In [26]:
import numpy as np
import time

# Define sizes
size = 1_000_000
matrix_size = 1000

# Generate data for lists and NumPy arrays
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]
array1 = np.arange(size)
array2 = np.arange(size)

# Element-wise Addition
start = time.time()
list_add = [list1[i] + list2[i] for i in range(size)]
end = time.time()
print(f"Python List Addition Time: {end - start:.5f} seconds")

start = time.time()
numpy_add = array1 + array2
end = time.time()
print(f"NumPy Array Addition Time: {end - start:.5f} seconds")

# Element-wise Multiplication
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print(f"Python List Multiplication Time: {end - start:.5f} seconds")

start = time.time()
numpy_mul = array1 * array2
end = time.time()
print(f"NumPy Array Multiplication Time: {end - start:.5f} seconds")

# Dot Product
start = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end = time.time()
print(f"Python List Dot Product Time: {end - start:.5f} seconds")

start = time.time()
dot_product_numpy = np.dot(array1, array2)
end = time.time()
print(f"NumPy Array Dot Product Time: {end - start:.5f} seconds")

# Matrix Multiplication
list_matrix1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
list_matrix2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
np_matrix1 = np.array(list_matrix1)
np_matrix2 = np.array(list_matrix2)

start = time.time()
result_matrix_list = [[sum(a * b for a, b in zip(row, col)) for col in zip(*list_matrix2)] for row in list_matrix1]
end = time.time()
print(f"Python List Matrix Multiplication Time: {end - start:.5f} seconds")

start = time.time()
result_matrix_numpy = np.matmul(np_matrix1, np_matrix2)
end = time.time()
print(f"NumPy Matrix Multiplication Time: {end - start:.5f} seconds")


Python List Addition Time: 0.18696 seconds
NumPy Array Addition Time: 0.00822 seconds
Python List Multiplication Time: 0.19813 seconds
NumPy Array Multiplication Time: 0.01558 seconds
Python List Dot Product Time: 0.06203 seconds
NumPy Array Dot Product Time: 0.00115 seconds
Python List Matrix Multiplication Time: 108.12782 seconds
NumPy Matrix Multiplication Time: 0.97885 seconds
